package phaser;

/**
 * Audio sprite sound type.
 *
 * @typedef {object} AudioSpriteSound
 *
 * @property {object} spritemap - Local reference to 'spritemap' object form json file generated by audiosprite tool.
 */
typedef AudioSpriteSound = {
var spritemap:Dynamic;
};
