package phaser.physics.arcade;

@:native("Phaser.Physics.Arcade.StaticBody")
extern class StaticBody {
    public function new(world:phaser.physics.arcade.World, gameObject:phaser.gameobjects.GameObject);
    public var world:phaser.physics.arcade.World;
    public var gameObject:phaser.gameobjects.GameObject;
    public var debugShowBody:Bool;
    public var debugBodyColor:Int;
    public var enable:Bool;
    public var isCircle:Bool;
    public var radius:Float;
    public var offset:phaser.math.Vector2;
    public var position:phaser.math.Vector2;
    public var width:Float;
    public var height:Float;
    public var halfWidth:Float;
    public var halfHeight:Float;
    public var center:phaser.math.Vector2;
    public var velocity:phaser.math.Vector2;
    public var allowGravity:Bool;
    public var gravity:phaser.math.Vector2;
    public var bounce:phaser.math.Vector2;
    public var onWorldBounds:Bool;
    public var onCollide:Bool;
    public var onOverlap:Bool;
    public var mass:Float;
    public var immovable:Bool;
    public var customSeparateX:Bool;
    public var customSeparateY:Bool;
    public var overlapX:Float;
    public var overlapY:Float;
    public var overlapR:Float;
    public var embedded:Bool;
    public var collideWorldBounds:Bool;
    public var checkCollision:ArcadeBodyCollision;
    public var touching:ArcadeBodyCollision;
    public var wasTouching:ArcadeBodyCollision;
    public var blocked:ArcadeBodyCollision;
    public var physicsType:Int;
    public var x:Float;
    public var y:Float;
    public var left:Float;
    public var right:Float;
    public var top:Float;
    public var bottom:Float;
    public function setGameObject(gameObject:phaser.gameobjects.GameObject, ?update:Bool):phaser.physics.arcade.StaticBody;
    public function updateFromGameObject():phaser.physics.arcade.StaticBody;
    public function setOffset(x:Float, y:Float):phaser.physics.arcade.StaticBody;
    public function setSize(width:Float, height:Float, ?offsetX:Float, ?offsetY:Float):phaser.physics.arcade.StaticBody;
    public function setCircle(radius:Float, ?offsetX:Float, ?offsetY:Float):phaser.physics.arcade.StaticBody;
    public function updateCenter():Void;
    public function reset(x:Float, y:Float):Void;
    public function stop():phaser.physics.arcade.StaticBody;
    public function getBounds(obj:ArcadeBodyBounds):ArcadeBodyBounds;
    public function hitTest(x:Float, y:Float):Bool;
    public function deltaAbsX():Float;
    public function deltaAbsY():Float;
    public function deltaX():Float;
    public function deltaY():Float;
    public function deltaZ():Float;
    public function destroy():Void;
    public function drawDebug(graphic:phaser.gameobjects.Graphics):Void;
    public function willDrawDebug():Bool;
    public function setMass(value:Float):phaser.physics.arcade.StaticBody;
}
